# Generated by Django 5.0.1 on 2024-01-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('guessed_letters', models.CharField(blank=True, default='', max_length=26)),
                ('attempts_left', models.IntegerField(default=6)),
            ],
        ),
    ]
