# Generated by Django 5.0.1 on 2024-01-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=9)),
                ('player_turn', models.CharField(max_length=1)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
