# Generated by Django 5.0.1 on 2024-01-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoegame',
            name='board',
            field=models.CharField(default='         ', max_length=9),
        ),
        migrations.AlterField(
            model_name='tictactoegame',
            name='player_turn',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
