# Generated by Django 5.0.1 on 2024-01-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0002_alter_tictactoegame_board_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicTacToeGame',
        ),
    ]
