# Generated by Django 5.0.1 on 2024-01-12 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventure', '0003_delete_adventuregamestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weapon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('game_over', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.player')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=255)),
                ('from_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='adventure.scene')),
                ('to_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='adventure.scene')),
            ],
        ),
    ]
