# Generated by Django 5.0.1 on 2024-01-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='from_scene',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='to_scene',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
