# Generated by Django 5.0.1 on 2024-01-12 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventure', '0005_remove_gameresult_player_remove_gameresult_scene_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('next_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_scene', to='adventure.scene')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.scene')),
            ],
        ),
    ]
