# Generated by Django 5.0.1 on 2024-01-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
    ]
