# Generated by Django 5.0.1 on 2024-01-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='option_1_destination',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='option_1_text',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='option_2_destination',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='option_2_text',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.scene')),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='options',
            field=models.ManyToManyField(to='adventure.option'),
        ),
    ]
